# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94cac11241fbaeb378dff4465cde7cbe"
name = "floatcart-pro"
application_url = "http://pvp8i6ljdc2w2l99ac012ma7.91.239.208.85.sslip.io"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_draft_orders,write_products"

[auth]
redirect_urls = ["http://pvp8i6ljdc2w2l99ac012ma7.91.239.208.85.sslip.io/auth/callback", "http://pvp8i6ljdc2w2l99ac012ma7.91.239.208.85.sslip.io/auth/shopify/callback", "http://pvp8i6ljdc2w2l99ac012ma7.91.239.208.85.sslip.io/api/auth/callback"]

[app_proxy]
url = "http://pvp8i6ljdc2w2l99ac012ma7.91.239.208.85.sslip.io/api/floating-cart"
subpath = "floatcart-pro"
prefix = "apps"
